Lxc networking
axsh/openvdc pull request #101
Opened 2017-01-31 04:15 UTC by b0r6

Okay so this makes it possible for the lxc-containers to connect to different bridge-types on startup.

When using ./openvdc run centos/7/lxc It's now required that the user  specifies a bridge-type.
Either by passing a .json file like so;  `./openvdc run centos/7/lxc @config.json` 
or by inputing the json directly: `./openvdc run centos/7/lxc '{"Interfaces":[{"bridge":"linux"}]}'`

Before starting the container, the hypervisor modifies the container's config file. If it fails to start the config file is reset. The lxc config file is given a different up and down-script depending on which bridge-type was chosen.

Bridge-names and up/down-scripts can be specified in the config file in `/etc/openvdc/executor.toml`

```
[bridges]
	[bridges.linux]
	name = "br0"
	up-script = "linux-bridge-up.sh"
	down-script = "linux-bridge-down.sh"

	[bridges.ovs]
	name = "ovs-vsctl"
	up-script = "ovs-up.sh"
	down-script = "ovs-down.sh"
```

2017-02-01 07:03 UTC, Metallion commented
Looks like there's a couple conflicts that need to be solved.

2017-02-01 07:05 UTC, b0r6 commented
Oh. I'll have a look.

2017-02-01 08:51 UTC, b0r6 commented
Solved.

2017-02-02 02:22 UTC, unakatsuo requested changes
Changes to cmd/openvdc/cmd/run.go should be reverted.

2017-02-07 08:58 UTC, unakatsuo approved these changes

2017-02-07 08:58 UTC, unakatsuo commented on hypervisor/lxc/lxc.go
> +
filepath.Join(settings.ScriptPath, settings.LinuxUpScript)

2017-02-07 08:58 UTC, unakatsuo commented on hypervisor/lxc/lxc.go
> +		os.Setenv("TAPNAME", nwi.TapName)
Env variable has process wide effect so that these code causes race issue potentially if the multiple tasks run. 

LXC gives some parameters to up/down script.

https://github.com/lxc/lxc/blob/4893a4315c551745108fedcd2433f4ea9ac87013/src/lxc/conf.c#L2681-L2683

I assume that the up/down script will receive the parameters following when they are invoked. But seems that there is no bridge name:

```
upscript.sh i-xxxxxxxxx net up veth veth1
```

If you still need to use custom env variable for up/down script, there is ``lxc.environment`` to preserve env variables inside the container. Downside is that the variables will be exposed to container user. It might be a risk.

https://linuxcontainers.org/lxc/manpages/man5/lxc.container.conf.5.html

Another way is that generating up/down script and save them to each container data folder, i.e. /var/lib/lxc/i-xxxxxxx/. The  script will be filled the bridge name when it is generated from template up/down script.


FYI. HEAD of LXC supports attaching to ovs from ``.link`` parameter. The change was added three years ago.

https://github.com/lxc/lxc/blame/8b7ffa302d15bfafe75a270c32b2287eb594ee22/src/lxc/network.c#L1470-L1471

2017-02-08 07:24 UTC, b0r6 commented on hypervisor/lxc/lxc.go
> +		os.Setenv("TAPNAME", nwi.TapName)
Wait, so lxc.network.link is compatible with ovs as well? I assumed it wasn't due to this: https://github.com/axsh/openvdc/issues/66

2017-02-08 09:55 UTC, unakatsuo commented on hypervisor/lxc/lxc.go
> +		os.Setenv("TAPNAME", nwi.TapName)
I'm using lxc-1.0.9 on CentOS7. 

```
$ rpm -qa  lxc
lxc-1.0.9-1.el7.x86_64
```
``ovs_*`` functions aren't there in v1.0.9. So please ignore my mention. 

https://github.com/lxc/lxc/blob/lxc-1.0.9/src/lxc/network.c

2017-02-08 10:46 UTC, b0r6 commented
Made a few changes;

* Env variables aren't used anymore.

* Up- and down-scripts are now created and placed in the containers folder (for example /var/lib/lxc/i-0000000085/up.sh)

* The default scripts located in /etc/openvdc/scripts are now by default blank, but whatever gets added to them gets added to the generated up- and down-scripts
Do we want the user to be able to customize the up- and down-scripts or not? If not, I'll remove them.

2017-02-15 16:03 UTC, unakatsuo commented
https://ci.openvdc.org/job/citest/job/lxc-networking/36/consoleText

```
Feb 16 00:19:43 executor-lxc kernel: IPv6: ADDRCONF(NETDEV_UP): i-0000000000: link is not ready
Feb 16 00:19:43 executor-lxc NetworkManager[405]: <warn>  (vethDQM2F2): failed to find device 4 'vethDQM2F2' with udev
Feb 16 00:19:43 executor-lxc NetworkManager[405]: <info>  (vethDQM2F2): new Veth device (carrier: OFF, driver: 'veth', ifindex: 4)
Feb 16 00:19:43 executor-lxc NetworkManager[405]: <warn>  (i-0000000000): failed to find device 5 'i-0000000000' with udev
Feb 16 00:19:43 executor-lxc NetworkManager[405]: <info>  (i-0000000000): new Veth device (carrier: OFF, driver: 'veth', ifindex: 5)
Feb 16 00:19:43 executor-lxc NetworkManager[405]: <warn>  (vethDQM2F2): failed to disable userspace IPv6LL address handling
Feb 16 00:19:43 executor-lxc NetworkManager[405]: <warn>  (i-0000000000): failed to disable userspace IPv6LL address handling
Feb 16 00:19:45 executor-lxc mesos-slave[802]: I0216 00:19:45.334784  1010 slave.cpp:5044] Current disk usage 4.95%. Max allowed age: 5.953717529715660days
Feb 16 00:19:48 executor-lxc mesos-slave[802]: I0216 00:19:48.241057  1010 slave.cpp:3634] Handling status update TASK_FAILED (UUID: 304b6f9c-f392-11e6-b224-525601000505) for task i-0000000000 of framework 8b84166a-e0bf-4cb3-bd55-2f1fde0305be-0000 from executor(1)@10.0.100.14:55963
Feb 16 00:19:48 executor-lxc mesos-slave[802]: I0216 00:19:48.243396  1010 status_update_manager.cpp:323] Received status update TASK_FAILED (UUID: 304b6f9c-f392-11e6-b224-525601000505) for task i-0000000000 of framework 8b84166a-e0bf-4cb3-bd55-2f1fde0305be-0000
Feb 16 00:19:48 executor-lxc mesos-slave[802]: I0216 00:19:48.243516  1010 slave.cpp:4051] Forwarding the update TASK_FAILED (UUID: 304b6f9c-f392-11e6-b224-525601000505) for task i-0000000000 of framework 8b84166a-e0bf-4cb3-bd55-2f1fde0305be-0000 to master@10.0.100.11:5050
Feb 16 00:19:48 executor-lxc mesos-slave[802]: I0216 00:19:48.243609  1010 slave.cpp:3961] Sending acknowledgement for status update TASK_FAILED (UUID: 304b6f9c-f392-11e6-b224-525601000505) for task i-0000000000 of framework 8b84166a-e0bf-4cb3-bd55-2f1fde0305be-0000 to executor(1)@10.0.100.14:55963
Feb 16 00:19:48 executor-lxc mesos-slave[802]: I0216 00:19:48.247794  1010 status_update_manager.cpp:395] Received status update acknowledgement (UUID: 304b6f9c-f392-11e6-b224-525601000505) for task i-0000000000 of framework 8b84166a-e0bf-4cb3-bd55-2f1fde0305be-0000
```

2017-02-17 05:16 UTC, unakatsuo commented
https://ci.openvdc.org/job/citest/job/lxc-networking/46/consoleText

```
Feb 17 13:28:20 executor-lxc vdc-executor[7931]: 2017-02-17 13:28:20 [DEBUG] github.com/axsh/openvdc/hypervisor/lxc/lxc.go:107 # Template used to create this container: /usr/share/lxc/templates/lxc-download
                                                 # Parameters passed to the template: --dist ubuntu --release trusty --arch amd64
                                                 # For additional config options, please look at lxc.container.conf(5)
                                                 
                                                 # Distribution configuration
                                                 lxc.include = /usr/share/lxc/config/ubuntu.common.conf
                                                 lxc.arch = x86_64
                                                 
                                                 # Container specific configuration
                                                 lxc.rootfs = /var/lib/lxc/i-0000000000/rootfs
                                                 lxc.utsname = i-0000000000
                                                 
                                                 # Network configuration
                                                 lxc.network.type = veth
                                                 lxc.network.flags = up
                                                 
                                                 
                                                 lxc.network.veth.pair=i-0000000000
                                                 lxc.network.script.up=/var/lib/lxc/i-0000000000/up.sh
                                                 lxc.network.script.down=/var/lib/lxc/i-0000000000/down.sh
                                                  hypervisor=lxc
Feb 17 13:28:20 executor-lxc vdc-executor[7931]: 2017-02-17 13:28:20 [INFO] openvdc-executor/main.go:139 Starting instance context=vdc-executor hypervisor=lxc instance_id=i-0000000000 state=STARTING
Feb 17 13:28:20 executor-lxc vdc-executor[7931]: 2017-02-17 13:28:20 [INFO] github.com/axsh/openvdc/hypervisor/lxc/lxc.go:321 Starting lxc-container... hypervisor=lxc
Feb 17 13:28:20 executor-lxc kernel: IPv6: ADDRCONF(NETDEV_UP): i-0000000000: link is not ready
Feb 17 13:28:20 executor-lxc NetworkManager[424]: <warn>  (vethLFJ0GA): failed to find device 4 'vethLFJ0GA' with udev
Feb 17 13:28:20 executor-lxc NetworkManager[424]: <info>  (vethLFJ0GA): new Veth device (carrier: OFF, driver: 'veth', ifindex: 4)
Feb 17 13:28:20 executor-lxc NetworkManager[424]: <warn>  (i-0000000000): failed to find device 5 'i-0000000000' with udev
Feb 17 13:28:20 executor-lxc NetworkManager[424]: <info>  (i-0000000000): new Veth device (carrier: OFF, driver: 'veth', ifindex: 5)
Feb 17 13:28:20 executor-lxc NetworkManager[424]: <warn>  (vethLFJ0GA): failed to disable userspace IPv6LL address handling
Feb 17 13:28:20 executor-lxc NetworkManager[424]: <warn>  (i-0000000000): failed to disable userspace IPv6LL address handling
Feb 17 13:28:25 executor-lxc vdc-executor[7931]: 2017-02-17 13:28:25 [ERROR] github.com/axsh/openvdc/hypervisor/lxc/lxc.go:323 starting the container failed hypervisor=lxc
Feb 17 13:28:25 executor-lxc vdc-executor[7931]: 2017-02-17 13:28:25 [ERROR] openvdc-executor/main.go:142 Failed StartInstance Error: starting the container failed context=vdc-executor hypervisor=lxc instance_id=i-0000000000 state=STARTING
Feb 17 13:28:25 executor-lxc vdc-executor[7931]: 2017-02-17 13:28:25 [ERROR] openvdc-executor/main.go:106 Failed Instances.UpdateState context=vdc-executor hypervisor=lxc instance_id=i-0000000000 state=REGISTERED
Feb 17 13:28:25 executor-lxc vdc-executor[7931]: 2017-02-17 13:28:25 [INFO] openvdc-executor/main.go:45 Registered Executor on slave  executor-lxc context=vdc-executor
```

2017-02-20 07:27 UTC, Metallion commented on ci/acceptance-test/tests/02_start_and_terminate_lxc_instance_test.go
> +	stdout, _ := RunCmdAndReportFail(t, "openvdc", "run", "centos/7/lxc", `{"interfaces":[{"type":"veth", "bridge":"linux"}]}`)
I've been thinking while using this code. Why does the user have to know what bridge type the instance will get attached to? Isn't it better to just configure that on the executor and let each executor handle it?

2017-02-21 09:26 UTC, unakatsuo commented on ci/acceptance-test/tests/02_start_and_terminate_lxc_instance_test.go
> +	stdout, _ := RunCmdAndReportFail(t, "openvdc", "run", "centos/7/lxc", `{"interfaces":[{"type":"veth", "bridge":"linux"}]}`)
``bridge`` is now optional parameter.

2017-02-21 11:54 UTC, unakatsuo commented
Confirmed on CI that renaming bridge name ``virbr0`` -> ``br0`` caused error.

https://ci.openvdc.org/job/citest/job/lxc-networking/75/console

Due to 7508514,  the modified config was not re-loaded so that the network configuration from ``/etc/lxc/default.conf`` remained effective.

2017-03-02 06:56 UTC, Metallion requested changes
I think some test scenarios should be added to this. Currently multiple nics and ovs are untested.

I suggest changing the acceptance test layout a bit. For example I don't we really need a `null` hypervisor executor. How about we instead convert that one into an executor with lxc and ovs?

That way we'll have 2 executors that both run LXC but one uses Linux bridge and the other uses Open vSwitch.

2017-03-22 03:35 UTC, Metallion commented
This really needs to get those extra test scenario's written so we can finally merge it.

2017-03-25 11:42 UTC, unakatsuo commented
#109 was resolved by around:
- 4af56bfbcea9
- 2c82522146e5
- 7e698a24efb6
- 08f1183e12ea

2017-03-28 06:14 UTC, Metallion commented
Still doesn't have tests for ovs but I guess I'll merge. :p I hope I'll find time to add a node to multibox with ovs so we can get that tested too.

2017-03-28 06:14 UTC, Metallion approved these changes

2017-03-28 06:15 UTC, merged