Local image
axsh/openvdc pull request #168
Opened 2017-05-22 11:32 UTC by b0r6

#162

2017-05-24 09:29 UTC, unakatsuo requested changes

2017-05-24 09:29 UTC, unakatsuo commented on cmd/lxc-openvdc/main.go
> -	lxcPath = "/usr/share/lxc/"
Here should be left as:

```
var lxcPath string
```

2017-05-24 09:35 UTC, b0r6 commented on cmd/lxc-openvdc/main.go
> -	lxcPath = "/usr/share/lxc/"
It's defined as that further up.

2017-05-24 09:52 UTC, unakatsuo commented on cmd/lxc-openvdc/main.go
> -	lxcPath = "/usr/share/lxc/"
Sorry. I missed that.

2017-05-24 09:52 UTC, unakatsuo approved these changes

2017-05-25 05:32 UTC, Metallion commented
Yay. \o/

2017-05-25 05:32 UTC, merged

2017-06-02 09:35 UTC, unakatsuo commented
https://ci.openvdc.org/blue/rest/organizations/jenkins/pipelines/citest/branches/master/runs/188/nodes/36/log/

```
=== RUN   TestLocalImage
--- FAIL: TestLocalImage (61.55s)
	00_ssh.go:77: STDOUT:
	00_ssh.go:78: STDERR:
		i-0000000012 doesn't exist
	00_ssh.go:80: Running 'sudo lxc-info -n i-0000000012' on '10.0.100.14' failed. Tried 10 times.
```

2017-06-02 09:39 UTC, unakatsuo commented on ci/citest/acceptance-test/tests/local_image_test.go
> +	stdout, _ := RunCmdAndReportFail(t, "openvdc", "run", "centos/7/lxc", `{"lxc_template":{"template":"openvdc"}}`)
Here is missing ``node_groups`` attribute to let the instance run on ``executor_lxc_ip`` 10.100.0.14.

```
`{"lxc_template":{"template":"openvdc"}, "node_groups":"linuxbr"}`
```