Changing the timing of key generation from run time to installation time
axsh/openvdc pull request #172
Opened 2017-05-26 08:42 UTC by itouri

2017-05-26 08:44 UTC, Metallion commented
* You need to merge origin/master into this branch and resolve the conflict in `sshd.go`.
* What happens when the user deletes the keys in `/etc/openvdc/ssh`?

2017-05-27 01:44 UTC, unakatsuo commented
https://ci.openvdc.org/blue/rest/organizations/jenkins/pipelines/citest/branches/executor-hostkey/runs/8/nodes/36/log

```
May 26 11:29:46 executor-lxc vdc-executor[12279]: 2017-05-26 11:29:46 [FATAL] openvdc-executor/main.go:569 Failed to setup SSH Server Error: /etc/openvdc/ssh/host_rsa_key is not a valid pem file: ssh: no key found
                                                  ErrorStackTrace:
                                                  main.(*SSHServer).Setup
                                                          /var/tmp/go/src/github.com/axsh/openvdc/cmd/openvdc-executor/sshd.go:56
                                                  main.execute
                                                          /var/tmp/go/src/github.com/axsh/openvdc/cmd/openvdc-executor/main.go:566
                                                  github.com/axsh/openvdc/vendor/github.com/spf13/cobra.(*Command).execute
                                                          /var/tmp/go/src/github.com/axsh/openvdc/vendor/github.com/spf13/cobra/command.go:636
                                                  github.com/axsh/openvdc/vendor/github.com/spf13/cobra.(*Command).ExecuteC
                                                          /var/tmp/go/src/github.com/axsh/openvdc/vendor/github.com/spf13/cobra/command.go:722
                                                  github.com/axsh/openvdc/vendor/github.com/spf13/cobra.(*Command).Execute
                                                          /var/tmp/go/src/github.com/axsh/openvdc/vendor/github.com/spf13/cobra/command.go:681
                                                  main.main
                                                          /var/tmp/go/src/github.com/axsh/openvdc/cmd/openvdc-executor/main.go:613
                                                  runtime.main
                                                          /usr/lib/golang/src/runtime/proc.go:183
                                                  runtime.goexit
                                                          /usr/lib/golang/src/runtime/asm_amd64.s:2086
```

2017-06-02 08:57 UTC, unakatsuo requested changes

2017-06-02 08:57 UTC, unakatsuo commented on cmd/openvdc-executor/sshd.go
> +	"/etc/openvdc/ssh/host_ed25519_key",
I want here to set at the build time. Please refer``build.go`` where overwrite go top level variables.

2017-06-02 08:57 UTC, unakatsuo commented on pkg/rhel/openvdc.spec
> +test ! -f /etc/openvdc/ssh/host_rsa_key && /usr/bin/ssh-keygen -q -t rsa -f /etc/openvdc/ssh/host_rsa_key -C '' -N '' >&/dev/null;
Please confirm the RSA key bit length. Want to set longer than 2048 bit.

2017-06-09 05:16 UTC, itouri commented on pkg/rhel/openvdc.spec
> +test ! -f /etc/openvdc/ssh/host_rsa_key && /usr/bin/ssh-keygen -q -t rsa -f /etc/openvdc/ssh/host_rsa_key -C '' -N '' >&/dev/null;
Default of rsa key size is 2048bit, therefore I'll modify the size of rsa key from 2048 to 4096.

2017-06-09 10:25 UTC, unakatsuo approved these changes

2017-06-09 10:27 UTC, merged