Template misc
axsh/openvdc pull request #180
Opened 2017-06-08 10:09 UTC by b0r6

* Added template that's set to 'openvdc'
* The local Image test checks which template was used for creating the container and fails if it's not 'lxc-openvdc'

2017-06-10 03:27 UTC, unakatsuo requested changes

2017-06-10 03:27 UTC, unakatsuo commented on ci/citest/acceptance-test/tests/local_image_test.go
> +	stdout, _ = RunCmdAndReportFail(t, "openvdc", "run", "https://raw.githubusercontent.com/axsh/openvdc/template-misc/templates/centos/7/lxc2.json", `{"node_groups":["linuxbr"]}`)
when this branch gets removed after merging, the test will fail. lxc2.json should be bundled as test fixtures.

Please refer:
- https://github.com/axsh/openvdc/tree/template-misc/ci/citest/acceptance-test/tests/fixtures
- https://github.com/axsh/openvdc/blob/template-misc/ci/citest/acceptance-test/tests/cmd_template_test.go#L11-L17

2017-06-10 03:27 UTC, unakatsuo commented on cmd/lxc-openvdc/main.go
> +		return errors.New(fmt.Sprintf("Url: %s Http status code: %s", downloadUrl, res.StatusCode))
errors.New() -> errors.Errorf()

https://github.com/pkg/errors/blob/master/errors.go#L111

2017-06-10 03:27 UTC, unakatsuo commented on ci/citest/acceptance-test/tests/local_image_test.go
> +	if templateUsed == "" || templateUsed != "lxc-openvdc" {
``templateUsed == ""`` is duplicate condition.

2017-06-10 03:27 UTC, unakatsuo commented on ci/citest/acceptance-test/tests/local_image_test.go
> +	t.Log(stdout.String())
Better to check if verbose flag is passed from command line when you put non-error messages.

```
if testing.Verbose() {
    t.Log(stdout.String())
}
```

2017-06-12 08:00 UTC, unakatsuo requested changes

2017-06-12 08:00 UTC, unakatsuo commented on cmd/lxc-openvdc/main.go
> +		return errors.Errorf(fmt.Sprintf("Url: %s Http status code: %s", downloadUrl, res.StatusCode))
you can remove ``fmt.Sprintf``

2017-06-12 08:02 UTC, b0r6 commented on cmd/lxc-openvdc/main.go
> +		return errors.Errorf(fmt.Sprintf("Url: %s Http status code: %s", downloadUrl, res.StatusCode))
Ah, missed that.

2017-06-12 09:01 UTC, unakatsuo approved these changes

2017-06-12 09:17 UTC, merged

2017-06-12 09:31 UTC, unakatsuo commented
For the future action,  ``lxc_template`` JSON field should allow the URI field for the base image if ``lxc-openvc`` is set.

```json
 "lxc_template": {
     "openvdc": {
         "image_uri": "https://example.com/centos7.x86_46.lxc.img.tgz",
         "sha256_sum": "abcdefabcedfabcedfabcedf"
      }
}
```