Fix local image tar issue
axsh/openvdc pull request #194
Opened 2017-07-27 09:34 UTC by Metallion

Mholt's archiver library that we were using to unpack the LXC rootfs tarball wasn't quite getting the job done. A rootfs contains a bunch of device nodes and other special files in the `/dev` directory. This library couldn't handle those properly and just wrote empty files instead.

I've checked out a couple other implementations but most seemed to just read the tarball, iterate over the files in it and then write new files with the same name and contents. While this works for the most basic archives, tarballs keep a lot more info such as ownership, permissions, etc.

I discussed with @unakatsuo and we decided to just use the tar command directly as there seems to be no sufficient go implementation and it's a safe bet that this lxc template will never be used outside of Linux.

2017-07-27 10:00 UTC, unakatsuo requested changes
Missing changes to the rpmspec file.

```
Requires: tar, xz, gzip
```

2017-07-28 05:29 UTC, Metallion commented
Oops, sorry about that. Will fix.

2017-07-28 06:39 UTC, unakatsuo approved these changes

2017-07-28 07:08 UTC, b0r6 approved these changes

2017-07-28 09:01 UTC, merged