Force destroy
axsh/openvdc pull request #213
Opened 2017-12-04 11:28 UTC by b0r6

```./openvdc destroy --force i-000000001```

This skips the state validation when trying to terminate the instance, making it possible to terminate them even though they might be stuck as RUNNING, for example.

2017-12-07 06:14 UTC, Metallion requested changes
Still needs test code. If it's possible to do just unit tests, I think that should be enough for a feature like this. If it's not possible, then maybe a small acceptance test.

Btw, would it also be possible to force other states? For example set an instance to RUNNING when it's stuck in STARTED because of a zookeeper connection error but the container/vm did come up correctly? (Doesn't necessarily need to be added to this PR)

2017-12-07 06:27 UTC, b0r6 commented
@Metallion 

> Still needs test code. If it's possible to do just unit tests, I think that should be enough for a feature like this. If it's not possible, then maybe a small acceptance test.
> 
> Btw, would it also be possible to force other states? For example set an instance to RUNNING when it's stuck in STARTED because of a zookeeper connection error but the container/vm did come up correctly? (Doesn't necessarily need to be added to this PR)

Alright, I'll add tests.

Yeah that wouldn't be hard to do I guess. Do you mean something like ```./openvdc forcestate RUNNING i-000000001```

2017-12-07 06:30 UTC, Metallion commented
Something like that, yes. Though I think it would be more intuitive to have the instance id before the state. The openvdc wait command does that too.

```
openvdc forcestate i-000000001 RUNNING
```

2017-12-19 09:12 UTC, Metallion approved these changes

2017-12-19 09:12 UTC, Metallion commented
Looks good to me but if possible, i'd still like to get somebody else to review the code.

2017-12-19 09:17 UTC, unakatsuo requested changes

2017-12-19 09:17 UTC, unakatsuo commented on cmd/openvdc/cmd/destroy.go
> +	Use:   "destroy [Instance ID] [options] [--] [commands]",
Does ``openvdc destroy`` accept extra command args?

2017-12-19 09:17 UTC, unakatsuo commented on ci/citest/acceptance-test/tests/force_destroy_test.go
> +	RunCmdAndReportFail(t, "openvdc", "force-state", instance_id, "starting")
Missing gofmt.

2017-12-21 08:28 UTC, unakatsuo approved these changes

2017-12-21 09:24 UTC, merged