Fix build script
axsh/openvdc pull request #33
Opened 2016-12-07 12:19 UTC by unakatsuo

- [x] schema.bindata.go should have the modtime from the last commit time.
- [x] Calucurate ``registry.GithubDefaultRef`` branch name from change history.

2016-12-09 06:19 UTC, Metallion requested changes

2016-12-09 06:19 UTC, Metallion commented on build.ps1
> +}
Why go to github at all? Why not use what we have in the local source code? That just seems so much simpler to me

2016-12-09 06:19 UTC, Metallion commented on build.sh
>  fi
Same thing here. Isn't it way more simple to use the local source code when needed?

2016-12-09 08:02 UTC, unakatsuo commented on build.ps1
> +}
The functionality is to work the CLI syntax following:

```
openvdc run centos/7/lxc
```

The the template file is assumed to be on remote server in this case and it is expected to be on github as default. During development, the "templates/" folder will be changed so we want to set the default branch to a topic branch. For release build, it should be ok with the master branch.

2016-12-09 08:11 UTC, Metallion commented on build.ps1
> +}
I think this kind of thinking will do more bad than good. It's much more user friendly to keep things simple and always default to the same templates which are kept on master.

To test other templates that are currently in development and on a remote server (ie a github branch) it should be enough to provide an absolute path/url.

Complicating this code will make it both error-prone and make it hard for users to know what the default templates repo is.

2016-12-22 09:47 UTC, Metallion commented on build.ps1
> +}
Discussed IRL and I realize I was wrong. Merging now. :+1:

2016-12-22 09:49 UTC, Metallion approved these changes

2016-12-22 09:49 UTC, merged