Scheduler local configuration file
axsh/openvdc pull request #94
Opened 2017-01-27 11:54 UTC by unakatsuo

2017-01-30 04:07 UTC, Metallion requested changes
Same comment as https://github.com/axsh/openvdc/pull/91. The `openvdc-scheduler` rpm package needs to install a default config file.

2017-01-30 07:03 UTC, Metallion commented on build.sh
> +go build -ldflags "$LDFLAGS -X 'main.DefaultConfPath=/etc/openvdc/scheduler.conf'" -v ./cmd/openvdc-scheduler
Why the .conf extension? In other places we're going with `toml` files so I think we should do it here too. I know viper supports multiple extensions and that's fine but let's use .toml for the default file.

2017-01-30 08:51 UTC, Metallion commented
We should remove the `pkg/rhel/sysconfig-openvdc` file since it is no longer used. Other than that I think it's good.

2017-01-30 23:19 UTC, unakatsuo commented
I have merged ``scheduler-config-file``. ``pkg/rhel/sysconfig-openvdc`` no longer exists. Applied same change for #91 as well.

2017-01-31 05:16 UTC, Metallion approved these changes

2017-01-31 05:16 UTC, merged